robot1:
  controller_manager:
    ros__parameters:
      update_rate: 100  # in Hz
      # use_sim_time: true # real hardware does not use sim_time

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        
      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

  joint_state_broadcaster:
    ros__parameters:
      joints:
        - robot1/front_left_wheel_joint
        - robot1/front_right_wheel_joint
        - robot1/rear_left_wheel_joint
        - robot1/rear_right_wheel_joint
      interfaces:
        - position
        - velocity

  diff_drive_controller:
    ros__parameters:
      use_stamped_vel: true

      left_wheel_names:
        - robot1/front_left_wheel_joint
        - robot1/rear_left_wheel_joint

      right_wheel_names:
        - robot1/front_right_wheel_joint
        - robot1/rear_right_wheel_joint

      wheel_separation: 0.40
      wheel_radius: 0.05
      publish_rate: 50.0

      base_frame_id: robot1/base_footprint
      odom_frame_id: robot1/odom
      enable_odom_tf: false

  imu_sensor_broadcaster:  # Comment this section when run on gazebo along with broadcaster
    ros__parameters:
      sensor_name: "imu_sensor"
      frame_id:  "robot1/imu_link"


robot2:
  controller_manager:
    ros__parameters:
      update_rate: 100  # in Hz
      # use_sim_time: true # real hardware does not use sim_time

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        
      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

  joint_state_broadcaster:
    ros__parameters:
      joints:
        - robot2/front_left_wheel_joint
        - robot2/front_right_wheel_joint
        - robot2/rear_left_wheel_joint
        - robot2/rear_right_wheel_joint
      interfaces:
        - position
        - velocity

  diff_drive_controller:
    ros__parameters:
      use_stamped_vel: true

      left_wheel_names:
        - robot2/front_left_wheel_joint
        - robot2/rear_left_wheel_joint

      right_wheel_names:
        - robot2/front_right_wheel_joint
        - robot2/rear_right_wheel_joint

      wheel_separation: 0.40
      wheel_radius: 0.05
      publish_rate: 50.0

      base_frame_id: robot2/base_footprint
      odom_frame_id: robot2/odom
      enable_odom_tf: false

  imu_sensor_broadcaster:  # Comment this section when run on gazebo along with broadcaster
    ros__parameters:
      sensor_name: "imu_sensor"
      frame_id:  "robot2/imu_link"
