robot_1:
  controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: false

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

  diff_drive_controller:
    ros__parameters:
      use_stamped_vel: false
      left_wheel_names:
        - "robot_1_front_left_wheel_joint"
        - "robot_1_rear_left_wheel_joint"
      right_wheel_names:
        - "robot_1_front_right_wheel_joint"
        - "robot_1_rear_right_wheel_joint"
      wheel_separation: 0.40
      wheel_radius: 0.05
      publish_rate: 50.0
      base_frame_id: "robot_1_base_footprint"
      odom_frame_id: "robot_1_odom"
      enable_odom_tf: false

  imu_sensor_broadcaster:
    ros__parameters:
      sensor_name: "robot_1_imu_sensor"
      frame_id:  "robot_1_imu_link"

robot_2:
  controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: false

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

  diff_drive_controller:
    ros__parameters:
      use_stamped_vel: true
      left_wheel_names:
        - "robot_2_front_left_wheel_joint"
        - "robot_2_rear_left_wheel_joint"
      right_wheel_names:
        - "robot_2_front_right_wheel_joint"
        - "robot_2_rear_right_wheel_joint"
      wheel_separation: 0.40
      wheel_radius: 0.05
      publish_rate: 50.0
      base_frame_id: "robot_2_base_footprint"
      odom_frame_id: "robot_2_odom"
      enable_odom_tf: false

  imu_sensor_broadcaster:
    ros__parameters:
      sensor_name: "robot_2_imu_sensor"
      frame_id:  "robot_2_imu_link"
