robot_1:
  controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: false
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

  diff_drive_controller:
    ros__parameters:
      left_wheel_names:
        - "robot_1_front_left_wheel_joint"
        - "robot_1_rear_left_wheel_joint"
      right_wheel_names:
        - "robot_1_front_right_wheel_joint"
        - "robot_1_rear_right_wheel_joint"
      wheel_separation: 0.40
      wheel_radius: 0.05
      base_frame_id: "robot_1_base_footprint"
      odom_frame_id: "robot_1/odom"
      enable_odom_tf: false
      position_feedback: true
      open_loop: false
      use_stamped_vel: false
      cmd_vel_timeout: 1.0
      publish_rate: 50.0
